name: auto merge

on: pull_request

jobs:
  merge-dependabot:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Merge Dependabot PRs
        run: gh pr merge "${GITHUB_HEAD_REF}" --merge --auto
